import {defineType} from 'sanity'

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'body', title: 'Body'},
    {name: 'portrait', title: 'Portrait'},
    {name: 'contact', title: 'Contact form'},
  ],
  fields: [
    {name: 'heroHeading', type: 'string', title: 'Hero heading', group: 'hero'},
    {
      name: 'heroSubhead',
      type: 'text',
      rows: 4,
      title: 'Hero subhead',
      group: 'hero',
    },
    {
      name: 'sections',
      type: 'array',
      title: 'Prose sections',
      group: 'body',
      of: [
        {
          type: 'object',
          name: 'aboutSection',
          fields: [
            {name: 'label', type: 'string', title: 'Side label (eyebrow)'},
            {name: 'heading', type: 'string', title: 'Heading'},
            {name: 'body', type: 'blockContent', title: 'Body'},
          ],
          preview: {select: {title: 'heading', subtitle: 'label'}},
        },
      ],
    },
    {
      name: 'portrait',
      type: 'image',
      title: 'Portrait image',
      group: 'portrait',
      options: {hotspot: true},
      fields: [{name: 'alt', type: 'string', title: 'Alt text'}],
    },
    {
      name: 'contactFormTitle',
      type: 'string',
      title: 'Contact form title',
      group: 'contact',
      initialValue: 'Get in touch',
    },
    {
      name: 'contactFormSubtitle',
      type: 'text',
      rows: 3,
      title: 'Contact form subtitle',
      group: 'contact',
    },
    {
      name: 'contactLeftLabel',
      type: 'string',
      title: 'Contact left column — eyebrow label',
      group: 'contact',
      description: 'Small uppercase label above the contact text. Defaults to "Get in touch".',
      initialValue: 'Get in touch',
    },
    {
      name: 'contactLeftPressIntro',
      type: 'text',
      rows: 2,
      title: 'Contact left — press intro line',
      group: 'contact',
      description: 'Short line above the press email link.',
    },
    {
      name: 'contactLeftPressEmail',
      type: 'string',
      title: 'Contact left — press email',
      group: 'contact',
      description: 'Email address rendered as a link below the press intro line.',
    },
    {
      name: 'contactLeftTipsIntro',
      type: 'text',
      rows: 2,
      title: 'Contact left — tips intro line',
      group: 'contact',
      description: 'Short line above the tips email link.',
    },
    {
      name: 'contactLeftTipsEmail',
      type: 'string',
      title: 'Contact left — tips email',
      group: 'contact',
      description: 'Email address rendered as a link below the tips intro line.',
    },
    {
      name: 'contactSuccessTitle',
      type: 'string',
      title: 'Success state title',
      group: 'contact',
      initialValue: 'Thank you.',
    },
    {
      name: 'contactSuccessBody',
      type: 'text',
      rows: 3,
      title: 'Success state body',
      group: 'contact',
    },
  ],
  preview: {prepare: () => ({title: 'About page'})},
})
